// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMePhotos.Data;

#nullable disable

namespace StockMePhotos.Data.Migrations
{
    [DbContext(typeof(StockMePhotosDbContext))]
    [Migration("20260216184620_SeedPhotosUploads")]
    partial class SeedPhotosUploads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0bb23ace-c418-4314-b8bb-09b3aeb9ab07",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5802101a-fe02-452b-a5ff-11f7b41f2bc6",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAECmwMRw016pLktP4Qaz0ZyqL//l3Ff29jJWz1Jf99Z4Sg5jnvzYmeYj79jE3gjN7Kg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d33ecd43-2588-4e33-8ab6-6fef7e149e40",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "97dfe4b4-8f5b-4a44-971d-6f62037bcde5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73599efc-a29b-4186-aee9-f3e4bbe924c6",
                            Email = "emilia@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILIA@EXAMPLE.COM",
                            NormalizedUserName = "EMILIA",
                            PasswordHash = "AQAAAAIAAYagAAAAEOheqDHS7vjez2PuBIh98mCz5Ht5arL43bpy9PZ+Nmxo2dMulEseid1fIeCUQ3h3TQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04c440c3-52f1-4128-bfbf-d1e150070bac",
                            TwoFactorEnabled = false,
                            UserName = "emilia"
                        },
                        new
                        {
                            Id = "75e1fd93-5f2d-4e72-8900-6ab9ed9ae323",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b708332-d7e2-4281-8fca-416b21d4827b",
                            Email = "WhaTheFuck@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WHATHEFUCK@EXAMPLE.COM",
                            NormalizedUserName = "WHATHEFUCK",
                            PasswordHash = "AQAAAAIAAYagAAAAEKaI9mKPuKFzOdLCLGUlGUzgnmEgntTsgf+7CZbPkQB/KkB/Lb15X/ki7LcTfvl18w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2aef82a-f765-4014-bccb-295fb0bccd71",
                            TwoFactorEnabled = false,
                            UserName = "WhaTheFuck"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Forests, mountains, beaches, sunsets, and outdoor scenery.",
                            Name = "Nature & Landscapes",
                            Slug = "nature-landscapes"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meals, desserts, beverages, and restaurant-style photography.",
                            Name = "Food & Drinks",
                            Slug = "food-drinks"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Everyday moments, portraits, work, family, and social life.",
                            Name = "People & Lifestyle",
                            Slug = "people-lifestyle"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Offices, devices, startups, teamwork, and digital life.",
                            Name = "Business & Technology",
                            Slug = "business-technology"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cities, landmarks, tourism, and cultural locations.",
                            Name = "Travel & Destinations",
                            Slug = "travel-destinations"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing, accessories, cosmetics, and style trends.",
                            Name = "Fashion & Beauty",
                            Slug = "fashion-beauty"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Training, workouts, competitions, and active lifestyles.",
                            Name = "Sports & Fitness",
                            Slug = "sports-fitness"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pets, farm animals, and wildlife in natural settings.",
                            Name = "Animals & Wildlife",
                            Slug = "animals-wildlife"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buildings, homes, offices, and interior design.",
                            Name = "Architecture & Interiors",
                            Slug = "architecture-interiors"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Painting, music, crafts, design, and creative expression.",
                            Name = "Art & Creativity",
                            Slug = "art-creativity"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Entity ID");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Entity IsDeleted flag");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Majestic lion resting in golden savannah grass.",
                            IsDeleted = false,
                            Slug = "lion-in-the-wild",
                            Title = "Lion in the Wild",
                            UserId = "75e1fd93-5f2d-4e72-8900-6ab9ed9ae323"
                        },
                        new
                        {
                            Id = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wild horse running freely across open fields.",
                            IsDeleted = false,
                            Slug = "running-horse",
                            Title = "Running Horse",
                            UserId = "97dfe4b4-8f5b-4a44-971d-6f62037bcde5"
                        },
                        new
                        {
                            Id = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clear river flowing between rocks and pine trees.",
                            IsDeleted = false,
                            Slug = "mountain-river",
                            Title = "Mountain River",
                            UserId = "97dfe4b4-8f5b-4a44-971d-6f62037bcde5"
                        },
                        new
                        {
                            Id = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "modern-glass-skyscraper",
                            IsDeleted = false,
                            Slug = "modern-glass-skyscraper",
                            Title = "Modern Glass Skyscraper",
                            UserId = "97dfe4b4-8f5b-4a44-971d-6f62037bcde5"
                        },
                        new
                        {
                            Id = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Old arched bridge crossing a calm river.",
                            IsDeleted = false,
                            Slug = "historic-stone-bridge",
                            Title = "Historic Stone Bridge",
                            UserId = "0bb23ace-c418-4314-b8bb-09b3aeb9ab07"
                        },
                        new
                        {
                            Id = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Powerful eagle soaring high above the mountains.",
                            IsDeleted = false,
                            Slug = "eagle-in-flight",
                            Title = "Eagle in Flight",
                            UserId = "75e1fd93-5f2d-4e72-8900-6ab9ed9ae323"
                        },
                        new
                        {
                            Id = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fans cheering inside a packed football stadium.",
                            IsDeleted = false,
                            Slug = "football-stadium-crowd",
                            Title = "Football Stadium Crowd",
                            UserId = "97dfe4b4-8f5b-4a44-971d-6f62037bcde5"
                        },
                        new
                        {
                            Id = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-level pagoda surrounded by autumn trees.",
                            IsDeleted = false,
                            Slug = "traditional-wooden-pagoda",
                            Title = "Traditional Wooden Pagoda",
                            UserId = "0bb23ace-c418-4314-b8bb-09b3aeb9ab07"
                        },
                        new
                        {
                            Id = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stone temple remains surrounded by jungle.",
                            IsDeleted = false,
                            Slug = "ancient-temple-ruins",
                            Title = "Ancient Temple Ruins",
                            UserId = "0bb23ace-c418-4314-b8bb-09b3aeb9ab07"
                        },
                        new
                        {
                            Id = new Guid("cef5077c-120a-4940-9db5-12781982d2f3"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sharp snowy mountain under a clear sky.",
                            IsDeleted = false,
                            Slug = "snowy-mountain-peak",
                            Title = "Snowy Mountain Peak",
                            UserId = "75e1fd93-5f2d-4e72-8900-6ab9ed9ae323"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PhotoId", "CategoryId")
                        .IsUnique();

                    b.ToTable("PhotosCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 8,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea")
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c")
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22")
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 9,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe")
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            PhotoId = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481")
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4")
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045")
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585")
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8")
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoUploads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264895/lion-in-the-wild_y6rzx0.webp",
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea")
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264382/running-horse_nk2imj.jpg",
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c")
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264388/mountain-river_qk7yll.avif",
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22")
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264699/modern-glass-skyscraper_f11xyq.jpg",
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe")
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265103/historic-stone-bridge_sncska.jpg",
                            PhotoId = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481")
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265186/eagle-in-flight_qykv4v.jpg",
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4")
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265564/football-stadium-crowd_zvvkso.jpg",
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045")
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265493/traditional-wooden-pagoda_zq5enw.jpg",
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585")
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265794/ancient-temple-ruins_xszn2q.jpg",
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8")
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265795/snowy-mountain-peak_njsdu5.jpg",
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sunset",
                            Slug = "sunset"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Portrait",
                            Slug = "portrait"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Minimal",
                            Slug = "minimal"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vintage",
                            Slug = "vintage"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Street",
                            Slug = "street"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aerial",
                            Slug = "aerial"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Black & White",
                            Slug = "black-white"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Night",
                            Slug = "night"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Macro",
                            Slug = "macro"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urban",
                            Slug = "urban"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoCategory", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Category", "Category")
                        .WithMany("PhotoCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithMany("PhotoCategories")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithOne("PhotoUpload")
                        .HasForeignKey("StockMePhotos.Data.Models.PhotoUpload", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Category", b =>
                {
                    b.Navigation("PhotoCategories");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Navigation("PhotoCategories");

                    b.Navigation("PhotoUpload");
                });
#pragma warning restore 612, 618
        }
    }
}
