// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMePhotos.Data;

#nullable disable

namespace StockMePhotos.Data.Migrations
{
    [DbContext(typeof(StockMePhotosDbContext))]
    [Migration("20260417181508_ExtendApplicationUser")]
    partial class ExtendApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5ac480a0-48c9-4eea-b6fb-7ba7f8e78c14",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDpezchkQAEjJ71X25R0fHsU4rUQrSM49lvXfxq2f5FCnkyWjnEbmFTO+UN2mcydvw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8f4a6c8-944b-4280-800b-99bd9dbf078a",
                            Email = "emilia@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILIA@EXAMPLE.COM",
                            NormalizedUserName = "EMILIA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF8XqtLWs9dMOWiZJJhB4WFyeCacLEd72sphn2aaiZSG7Q7Y2VVCBypEjXcWPNemTQ==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "emilia"
                        },
                        new
                        {
                            Id = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50db99a6-4108-48f1-8e52-b6ee50c84727",
                            Email = "WhaTheFuck@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "WHATHEFUCK@EXAMPLE.COM",
                            NormalizedUserName = "WHATHEFUCK@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC2DZ9H+kZeCUmykgkceRHR+QHZAbnkiPgaKrRsV4a/N2YRUWRFd5n281c6D+mmuiw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "WhaTheFuck"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Forests, mountains, beaches, sunsets, and outdoor scenery.",
                            Name = "Nature & Landscapes",
                            Slug = "nature-landscapes"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meals, desserts, beverages, and restaurant-style photography.",
                            Name = "Food & Drinks",
                            Slug = "food-drinks"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Everyday moments, portraits, work, family, and social life.",
                            Name = "People & Lifestyle",
                            Slug = "people-lifestyle"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Offices, devices, startups, teamwork, and digital life.",
                            Name = "Business & Technology",
                            Slug = "business-technology"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cities, landmarks, tourism, and cultural locations.",
                            Name = "Travel & Destinations",
                            Slug = "travel-destinations"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing, accessories, cosmetics, and style trends.",
                            Name = "Fashion & Beauty",
                            Slug = "fashion-beauty"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Training, workouts, competitions, and active lifestyles.",
                            Name = "Sports & Fitness",
                            Slug = "sports-fitness"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pets, farm animals, and wildlife in natural settings.",
                            Name = "Animals & Wildlife",
                            Slug = "animals-wildlife"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buildings, homes, offices, and interior design.",
                            Name = "Architecture & Interiors",
                            Slug = "architecture-interiors"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Painting, music, crafts, design, and creative expression.",
                            Name = "Art & Creativity",
                            Slug = "art-creativity"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.FavoritePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PhotoId", "UserId")
                        .IsUnique();

                    b.ToTable("FavoritePhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            UserId = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323")
                        },
                        new
                        {
                            Id = 2,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            UserId = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323")
                        },
                        new
                        {
                            Id = 3,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = 4,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = 5,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = 6,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = 7,
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = 8,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Entity ID");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Entity IsDeleted flag");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Majestic lion resting in golden savannah grass.",
                            IsDeleted = false,
                            Slug = "lion-in-the-wild",
                            Title = "Lion in the Wild",
                            UserId = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323")
                        },
                        new
                        {
                            Id = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wild horse running freely across open fields.",
                            IsDeleted = false,
                            Slug = "running-horse",
                            Title = "Running Horse",
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clear river flowing between rocks and pine trees.",
                            IsDeleted = false,
                            Slug = "mountain-river",
                            Title = "Mountain River",
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "modern-glass-skyscraper",
                            IsDeleted = false,
                            Slug = "modern-glass-skyscraper",
                            Title = "Modern Glass Skyscraper",
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Old arched bridge crossing a calm river.",
                            IsDeleted = false,
                            Slug = "historic-stone-bridge",
                            Title = "Historic Stone Bridge",
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Powerful eagle soaring high above the mountains.",
                            IsDeleted = false,
                            Slug = "eagle-in-flight",
                            Title = "Eagle in Flight",
                            UserId = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323")
                        },
                        new
                        {
                            Id = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fans cheering inside a packed football stadium.",
                            IsDeleted = false,
                            Slug = "football-stadium-crowd",
                            Title = "Football Stadium Crowd",
                            UserId = new Guid("97dfe4b4-8f5b-4a44-971d-6f62037bcde5")
                        },
                        new
                        {
                            Id = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-level pagoda surrounded by autumn trees.",
                            IsDeleted = false,
                            Slug = "traditional-wooden-pagoda",
                            Title = "Traditional Wooden Pagoda",
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stone temple remains surrounded by jungle.",
                            IsDeleted = false,
                            Slug = "ancient-temple-ruins",
                            Title = "Ancient Temple Ruins",
                            UserId = new Guid("0bb23ace-c418-4314-b8bb-09b3aeb9ab07")
                        },
                        new
                        {
                            Id = new Guid("cef5077c-120a-4940-9db5-12781982d2f3"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sharp snowy mountain under a clear sky.",
                            IsDeleted = false,
                            Slug = "snowy-mountain-peak",
                            Title = "Snowy Mountain Peak",
                            UserId = new Guid("75e1fd93-5f2d-4e72-8900-6ab9ed9ae323")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PhotoId", "CategoryId")
                        .IsUnique();

                    b.ToTable("PhotosCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 8,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea")
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c")
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22")
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 9,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe")
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            PhotoId = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481")
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 8,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4")
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045")
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585")
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8")
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("PhotoId", "TagId")
                        .IsUnique();

                    b.ToTable("PhotosTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            TagId = 11
                        },
                        new
                        {
                            Id = 2,
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            TagId = 12
                        },
                        new
                        {
                            Id = 3,
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c"),
                            TagId = 11
                        },
                        new
                        {
                            Id = 4,
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c"),
                            TagId = 12
                        },
                        new
                        {
                            Id = 5,
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22"),
                            TagId = 12
                        },
                        new
                        {
                            Id = 6,
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22"),
                            TagId = 15
                        },
                        new
                        {
                            Id = 7,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            TagId = 5
                        },
                        new
                        {
                            Id = 8,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            TagId = 10
                        },
                        new
                        {
                            Id = 9,
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            TagId = 15
                        },
                        new
                        {
                            Id = 10,
                            PhotoId = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481"),
                            TagId = 13
                        },
                        new
                        {
                            Id = 11,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            TagId = 11
                        },
                        new
                        {
                            Id = 12,
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            TagId = 12
                        },
                        new
                        {
                            Id = 13,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            TagId = 10
                        },
                        new
                        {
                            Id = 14,
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            TagId = 14
                        },
                        new
                        {
                            Id = 15,
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            TagId = 4
                        },
                        new
                        {
                            Id = 16,
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            TagId = 13
                        },
                        new
                        {
                            Id = 17,
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8"),
                            TagId = 4
                        },
                        new
                        {
                            Id = 18,
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8"),
                            TagId = 13
                        },
                        new
                        {
                            Id = 19,
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3"),
                            TagId = 12
                        },
                        new
                        {
                            Id = 20,
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3"),
                            TagId = 15
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoUploads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264895/lion-in-the-wild_y6rzx0.webp",
                            PhotoId = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea")
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264382/running-horse_nk2imj.jpg",
                            PhotoId = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c")
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264388/mountain-river_qk7yll.avif",
                            PhotoId = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22")
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771264699/modern-glass-skyscraper_f11xyq.jpg",
                            PhotoId = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe")
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265103/historic-stone-bridge_sncska.jpg",
                            PhotoId = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481")
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265186/eagle-in-flight_qykv4v.jpg",
                            PhotoId = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4")
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265564/football-stadium-crowd_zvvkso.jpg",
                            PhotoId = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045")
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265493/traditional-wooden-pagoda_zq5enw.jpg",
                            PhotoId = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585")
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265794/ancient-temple-ruins_xszn2q.jpg",
                            PhotoId = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8")
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://res.cloudinary.com/ddrcfggwn/image/upload/v1771265795/snowy-mountain-peak_njsdu5.jpg",
                            PhotoId = new Guid("cef5077c-120a-4940-9db5-12781982d2f3")
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sunset",
                            Slug = "sunset"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Portrait",
                            Slug = "portrait"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Minimal",
                            Slug = "minimal"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vintage",
                            Slug = "vintage"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Street",
                            Slug = "street"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aerial",
                            Slug = "aerial"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Black & White",
                            Slug = "black-white"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Night",
                            Slug = "night"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Macro",
                            Slug = "macro"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urban",
                            Slug = "urban"
                        },
                        new
                        {
                            Id = 11,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Animal",
                            Slug = "animal"
                        },
                        new
                        {
                            Id = 12,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nature",
                            Slug = "nature"
                        },
                        new
                        {
                            Id = 13,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Architecture",
                            Slug = "architecture"
                        },
                        new
                        {
                            Id = 14,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stadium",
                            Slug = "stadium"
                        },
                        new
                        {
                            Id = 15,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Landscape",
                            Slug = "landscape"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.FavoritePhoto", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithMany("ToFavorites")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", "User")
                        .WithMany("FavoritePhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.ApplicationUser", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoCategory", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Category", "Category")
                        .WithMany("PhotoCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithMany("PhotoCategories")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoTag", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMePhotos.Data.Models.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithOne("PhotoUpload")
                        .HasForeignKey("StockMePhotos.Data.Models.PhotoUpload", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FavoritePhotos");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Category", b =>
                {
                    b.Navigation("PhotoCategories");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Navigation("PhotoCategories");

                    b.Navigation("PhotoTags");

                    b.Navigation("PhotoUpload");

                    b.Navigation("ToFavorites");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });
#pragma warning restore 612, 618
        }
    }
}
