// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMePhotos.Data;

#nullable disable

namespace StockMePhotos.Data.Migrations
{
    [DbContext(typeof(StockMePhotosDbContext))]
    [Migration("20260215190448_SeedPhotos")]
    partial class SeedPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMePhotos.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Forests, mountains, beaches, sunsets, and outdoor scenery.",
                            Name = "Nature & Landscapes",
                            Slug = "nature-landscapes"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meals, desserts, beverages, and restaurant-style photography.",
                            Name = "Food & Drinks",
                            Slug = "food-drinks"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Everyday moments, portraits, work, family, and social life.",
                            Name = "People & Lifestyle",
                            Slug = "people-lifestyle"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Offices, devices, startups, teamwork, and digital life.",
                            Name = "Business & Technology",
                            Slug = "business-technology"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cities, landmarks, tourism, and cultural locations.",
                            Name = "Travel & Destinations",
                            Slug = "travel-destinations"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothing, accessories, cosmetics, and style trends.",
                            Name = "Fashion & Beauty",
                            Slug = "fashion-beauty"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Training, workouts, competitions, and active lifestyles.",
                            Name = "Sports & Fitness",
                            Slug = "sports-fitness"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pets, farm animals, and wildlife in natural settings.",
                            Name = "Animals & Wildlife",
                            Slug = "animals-wildlife"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buildings, homes, offices, and interior design.",
                            Name = "Architecture & Interiors",
                            Slug = "architecture-interiors"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Painting, music, crafts, design, and creative expression.",
                            Name = "Art & Creativity",
                            Slug = "art-creativity"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Entity ID");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Entity IsDeleted flag");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2161d2-92c0-4511-b390-7b3a862d72ea"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Majestic lion resting in golden savannah grass.",
                            IsDeleted = false,
                            Slug = "lion-in-the-wild",
                            Title = "Lion in the Wild"
                        },
                        new
                        {
                            Id = new Guid("398ac8ba-b365-495e-95ca-8d2d17c5065c"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wild horse running freely across open fields.",
                            IsDeleted = false,
                            Slug = "running-horse",
                            Title = "Running Horse"
                        },
                        new
                        {
                            Id = new Guid("3606010e-60d1-467e-b85f-1c93bd1a2c22"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clear river flowing between rocks and pine trees.",
                            IsDeleted = false,
                            Slug = "mountain-river",
                            Title = "Mountain River"
                        },
                        new
                        {
                            Id = new Guid("0c71e3e7-b60a-4633-a906-0e996724f4fe"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "modern-glass-skyscraper",
                            IsDeleted = false,
                            Slug = "modern-glass-skyscraper",
                            Title = "Modern Glass Skyscraper"
                        },
                        new
                        {
                            Id = new Guid("c6031c0d-d5f9-4434-b0ec-b40481613481"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Old arched bridge crossing a calm river.",
                            IsDeleted = false,
                            Slug = "historic-stone-bridge",
                            Title = "Historic Stone Bridge"
                        },
                        new
                        {
                            Id = new Guid("97e1fee6-c879-4b66-a1c2-3804d736cdf4"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Powerful eagle soaring high above the mountains.",
                            IsDeleted = false,
                            Slug = "eagle-in-flight",
                            Title = "Eagle in Flight"
                        },
                        new
                        {
                            Id = new Guid("0b1c7a4e-9b2e-4f6c-bc41-d1d6f42c6045"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fans cheering inside a packed football stadium.",
                            IsDeleted = false,
                            Slug = "football-stadium-crowd",
                            Title = "Football Stadium Crowd"
                        },
                        new
                        {
                            Id = new Guid("b192d3de-8452-4b11-9e2f-fa66a2216585"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-level pagoda surrounded by autumn trees.",
                            IsDeleted = false,
                            Slug = "traditional-wooden-pagoda",
                            Title = "Traditional Wooden Pagoda"
                        },
                        new
                        {
                            Id = new Guid("c0f0fc5a-1a7c-416e-8f00-0a1f4bedead8"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stone temple remains surrounded by jungle.",
                            IsDeleted = false,
                            Slug = "ancient-temple-ruins",
                            Title = "Ancient Temple Ruins"
                        },
                        new
                        {
                            Id = new Guid("cef5077c-120a-4940-9db5-12781982d2f3"),
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sharp snowy mountain under a clear sky.",
                            IsDeleted = false,
                            Slug = "snowy-mountain-peak",
                            Title = "Snowy Mountain Peak"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoUploads");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Entity ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sunset",
                            Slug = "sunset"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Portrait",
                            Slug = "portrait"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Minimal",
                            Slug = "minimal"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vintage",
                            Slug = "vintage"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Street",
                            Slug = "street"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aerial",
                            Slug = "aerial"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Black & White",
                            Slug = "black-white"
                        },
                        new
                        {
                            Id = 8,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Night",
                            Slug = "night"
                        },
                        new
                        {
                            Id = 9,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Macro",
                            Slug = "macro"
                        },
                        new
                        {
                            Id = 10,
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Urban",
                            Slug = "urban"
                        });
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.PhotoUpload", b =>
                {
                    b.HasOne("StockMePhotos.Data.Models.Photo", "Photo")
                        .WithOne("PhotoUpload")
                        .HasForeignKey("StockMePhotos.Data.Models.PhotoUpload", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("StockMePhotos.Data.Models.Photo", b =>
                {
                    b.Navigation("PhotoUpload");
                });
#pragma warning restore 612, 618
        }
    }
}
